<script setup lang="ts">
import AppLayout from '@/components/AppLayout.vue'
import AppPanel from '@/components/AppPanel.vue'
import { toGbp } from '@/utils/formatters'
import { aerToMonthly } from '@/utils/maths'
import {
  Checkbox,
  InputGroup,
  InputGroupAddon,
  InputNumber,
  Message,
  RadioButton,
  ScrollTop,
} from 'primevue'
import { computed, ref } from 'vue'

const years = ref(10)

const propertyInitialValue = ref(144444)
const propertyPurchaseFeePercentage = ref(5)
const propertyAnnualAppreciationRatePercentage = ref(3)
const propertyAnnualMaintenanceCostPercentage = ref(1)
const propertyCashOutFeePercentage = ref(5)

const propertyInitialPurchasePrice = computed(
  () => propertyInitialValue.value * (1 + propertyPurchaseFeePercentage.value / 100),
)

const propertyMonthlyMaintenanceCostPercentage = computed(() =>
  aerToMonthly(propertyAnnualMaintenanceCostPercentage.value),
)

const propertyMonthlyAppreciationRatePercentage = computed(() =>
  aerToMonthly(propertyAnnualAppreciationRatePercentage.value),
)

const mortgageAmount = ref(130000)
const mortgageInterestRate = ref(4.5)
const mortgageTerm = ref(10)

const mortgageMonthlyPayment = computed(() => {
  // Generated by Copilot!
  const monthlyInterestRate = mortgageInterestRate.value / 100 / 12
  const totalPayments = mortgageTerm.value * 12
  const monthlyPayment =
    (mortgageAmount.value * monthlyInterestRate) /
    (1 - Math.pow(1 + monthlyInterestRate, -totalPayments))

  return monthlyPayment
})

const intitialCashBalance = computed(
  () => propertyInitialPurchasePrice.value - mortgageAmount.value,
)

const cols = ref({
  days: false,
  months: false,
  years: true,
  day: false,
  month: false,
  year: false,
  propertyValue: true,
  propertyPurchaseFee: true,
  propertyPurchasePrice: true,
  propertyMonthlyMaintenaceCost: false,
  propertyMaintenanceCashSpent: true,
  propertyClosingFees: true,
  propertyCashOutValue: true,
  mortgageDebt: true,
  mortgagePaid: true,
  cashAvailable: true,
  cashSpent: true,
  cashProfit: true,
})

const groupBy = ref('years')

const breakdown = computed(() => {
  let propertyValue = propertyInitialValue.value

  let propertyMaintenanceCashSpent = 0
  let propertyMonthlyMaintenaceCost =
    propertyValue * (propertyMonthlyMaintenanceCostPercentage.value / 100)

  let mortgageDebt = mortgageAmount.value
  let mortgagePaid = 0

  return Array.from({ length: years.value * 360 + 1 }, (_, i) => {
    const days = i
    const months = Math.floor(i / 30)
    const years = Math.floor(i / 360)

    const day = days + 1
    const month = months + 1
    const year = years + 1

    const isFirstDayOfMonth = day % 30 === 1

    if (isFirstDayOfMonth && months > 0) {
      propertyMaintenanceCashSpent += propertyMonthlyMaintenaceCost

      propertyValue *= 1 + propertyMonthlyAppreciationRatePercentage.value / 100

      propertyMonthlyMaintenaceCost =
        propertyValue * (propertyMonthlyMaintenanceCostPercentage.value / 100)

      if (years <= mortgageTerm.value) {
        mortgageDebt *= 1 + mortgageInterestRate.value / 100 / 12
        mortgageDebt -= mortgageMonthlyPayment.value

        mortgagePaid += mortgageMonthlyPayment.value
      }
    }

    const propertyPurchaseFee = propertyValue * (propertyPurchaseFeePercentage.value / 100)
    const propertyPurchasePrice = propertyValue + propertyPurchaseFee
    const propertyCashOutFee = propertyValue * (propertyCashOutFeePercentage.value / 100)
    const propertyCashOutValue = propertyValue - propertyCashOutFee

    const cashAvailable = propertyCashOutValue - mortgageDebt
    const cashSpent =
      propertyInitialPurchasePrice.value -
      mortgageAmount.value +
      propertyMaintenanceCashSpent +
      mortgagePaid
    const cashProfit = cashAvailable - cashSpent

    return {
      days,
      months,
      years,
      day,
      month,
      year,
      propertyValue: toGbp(propertyValue),
      propertyPurchaseFee: toGbp(propertyPurchaseFee),
      propertyPurchasePrice: toGbp(propertyPurchasePrice),
      propertyMonthlyMaintenaceCost: toGbp(propertyMonthlyMaintenaceCost),
      propertyMaintenanceCashSpent: toGbp(propertyMaintenanceCashSpent),
      propertyClosingFees: toGbp(propertyCashOutFee),
      propertyCashOutValue: toGbp(propertyCashOutValue),
      mortgageDebt: toGbp(Math.max(0, mortgageDebt)),
      mortgagePaid: toGbp(mortgagePaid),
      cashAvailable: toGbp(cashAvailable),
      cashSpent: toGbp(Math.max(0, cashSpent)),
      cashProfit: toGbp(cashProfit),
    }
  })
})

const rows = computed(() => {
  if (groupBy.value === 'months') {
    return breakdown.value.filter((row) => row.days % 30 === 0)
  }

  if (groupBy.value === 'years') {
    return breakdown.value.filter((row) => row.days % 360 === 0)
  }

  return breakdown.value
})
</script>

<template>
  <AppLayout>
    <main class="section space-y-4">
      <AppPanel heading="Settings" expandable expanded>
        <div class="space-y-4">
          <div class="space-y-2">
            <label for="years">Period</label>
            <InputGroup>
              <InputNumber input-id="years" v-model="years" :min="1" :max-fraction-digits="0" />
              <InputGroupAddon>years</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter how many years you want to show.
            </Message>
          </div>
        </div>
      </AppPanel>

      <AppPanel heading="Property" expandable expanded>
        <div class="space-y-4">
          <div class="space-y-2">
            <label for="property_initial_value">Value</label>
            <InputGroup>
              <InputGroupAddon>£</InputGroupAddon>
              <InputNumber
                input-id="property_initial_value"
                v-model="propertyInitialValue"
                :min-fraction-digits="2"
                :max-fraction-digits="2"
              />
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter the initial value of your property.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_purchase_fee_percentage">Purchase Fee</label>
            <InputGroup>
              <InputNumber
                input-id="property_purchase_fee_percentage"
                v-model="propertyPurchaseFeePercentage"
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter the fee associated with purchasing the property as a percentage of the property
              value.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_initial_purchase_price">Purchase Price</label>
            <InputGroup>
              <InputGroupAddon>£</InputGroupAddon>
              <InputNumber
                input-id="property_initial_purchase_price"
                :model-value="propertyInitialPurchasePrice"
                disabled
                :min-fraction-digits="2"
                :max-fraction-digits="2"
              />
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              This is the total amount that it cost to buy the property, including its value and any
              purchase fee.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_annual_maintenance_cost_percentage">
              Annual Maintenance Cost
            </label>
            <InputGroup>
              <InputNumber
                input-id="property_annual_maintenance_cost_percentage"
                v-model="propertyAnnualMaintenanceCostPercentage"
                :min="0"
                :max="100"
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter the estimated cost of maintaining the property each year as a percentage of the
              property.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_monthly_maintenance_cost_percentage">
              Monthly Maintenance Cost
            </label>
            <InputGroup>
              <InputNumber
                input-id="property_monthly_maintenance_cost_percentage"
                :model-value="propertyMonthlyMaintenanceCostPercentage"
                disabled
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              This is the cost of maintaining the property each month as a percentage of the
              property.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_annual_appreciation_rate_percentage"
              >Annual Appreciation Rate</label
            >
            <InputGroup>
              <InputNumber
                input-id="property_annual_appreciation_rate_percentage"
                v-model="propertyAnnualAppreciationRatePercentage"
                :max="100"
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter the expected appreciation rate of your property.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_monthly_appreciation_rate_percentage">
              Monthly Appreciation Rate
            </label>
            <InputGroup>
              <InputNumber
                input-id="property_monthly_appreciation_rate_percentage"
                :model-value="propertyMonthlyAppreciationRatePercentage"
                disabled
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter the expected appreciation rate of your property.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="property_cash_out_fee_percentage">Cash Out Fee</label>
            <InputGroup>
              <InputNumber
                input-id="property_cash_out_fee_percentage"
                v-model="propertyCashOutFeePercentage"
                :min="0"
                :max="100"
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter the fee associated with selling the property as a percentage of the property
              value.
            </Message>
          </div>
        </div>
      </AppPanel>

      <AppPanel heading="Mortgage" expandable expanded>
        <div class="space-y-4">
          <div class="space-y-2">
            <label for="mortgage_amount">Amount</label>
            <InputGroup>
              <InputGroupAddon>£</InputGroupAddon>
              <InputNumber
                input-id="mortgage_amount"
                v-model="mortgageAmount"
                :min-fraction-digits="2"
                :max-fraction-digits="2"
              />
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter how much you want to borrow.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="mortgage_interest">Interest Rate</label>
            <InputGroup>
              <InputNumber
                input-id="mortgage_interest"
                v-model="mortgageInterestRate"
                :min="0"
                :max="100"
                :max-fraction-digits="2"
              />
              <InputGroupAddon>%</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter your mortgage interest rate.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="mortgage_term">Term</label>
            <InputGroup>
              <InputNumber input-id="mortgage_term" v-model="mortgageTerm" :min="1" />
              <InputGroupAddon>years</InputGroupAddon>
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              Enter your mortgage term in years.
            </Message>
          </div>

          <div class="space-y-2">
            <label for="mortgage_monthly_payment">Monthly Payment</label>
            <InputGroup>
              <InputGroupAddon>£</InputGroupAddon>
              <InputNumber
                input-id="mortgage_monthly_payment"
                :model-value="mortgageMonthlyPayment"
                disabled
                :min-fraction-digits="2"
                :max-fraction-digits="2"
              />
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              This is how much you'll pay each month towards your mortgage.
            </Message>
          </div>
        </div>
      </AppPanel>

      <AppPanel heading="Initial Values" expandable expanded>
        <div class="space-y-4">
          <div class="space-y-2">
            <label for="initial_cash_balance">Cash Balance</label>
            <InputGroup>
              <InputGroupAddon>£</InputGroupAddon>
              <InputNumber
                input-id="initial_cash_balance"
                :model-value="intitialCashBalance"
                disabled
                :min-fraction-digits="2"
                :max-fraction-digits="2"
              />
            </InputGroup>
            <Message size="small" severity="secondary" variant="simple">
              The cash you'll need upfront need is the sum of the money that's missing each time you
              purchase an investment. For example, if you purchase a property worth £100,000 without
              taking a loan, then you'll need £100,000 in cash. If you purchase a property worth
              £100,000 using a loan of £80,000, then sell the property for a profit of £10,000 and
              buy another property for £20,000, then you'll need to start with £30,000 in cash.
            </Message>
          </div>
        </div>
      </AppPanel>

      <AppPanel heading="Results" expandable expanded>
        <div class="space-y-4">
          <div class="flex items-top gap-4">
            <div class="font-medium">Columns:</div>

            <div class="flex items-center gap-x-2 gap-y-4 flex-wrap flex-1">
              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.days" binary input-id="days_col" />
                <label for="days_col">Days</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.months" binary input-id="months_col" />
                <label for="months_col">Months</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.years" binary input-id="years_col" />
                <label for="years_col">Years</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.day" binary input-id="day_col" />
                <label for="day_col">Day</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.month" binary input-id="month_col" />
                <label for="month_col">Month</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.year" binary input-id="year_col" />
                <label for="year_col">Year</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.propertyValue" binary input-id="property_value_col" />
                <label for="property_value_col">Property Value</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox
                  v-model="cols.propertyPurchaseFee"
                  binary
                  input-id="property_purchase_fee_col"
                />
                <label for="property_purchase_fee_col">Property Purchase Fee</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox
                  v-model="cols.propertyPurchasePrice"
                  binary
                  input-id="property_purchase_price_col"
                />
                <label for="property_purchase_price_col">Property Purchase Price</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox
                  v-model="cols.propertyMonthlyMaintenaceCost"
                  binary
                  input-id="property_monthly_maintenace_cost_col"
                />
                <label for="property_monthly_maintenace_cost_col"
                  >Property Monthly Maintenace Cost</label
                >
              </div>

              <div class="flex items-center gap-2">
                <Checkbox
                  v-model="cols.propertyMaintenanceCashSpent"
                  binary
                  input-id="property_maintenance_cash_spent_col"
                />
                <label for="property_maintenance_cash_spent_col"
                  >Property Maintenance Cash Spent</label
                >
              </div>

              <div class="flex items-center gap-2">
                <Checkbox
                  v-model="cols.propertyClosingFees"
                  binary
                  input-id="property_closing_fees_col"
                />
                <label for="property_closing_fees_col">Property Closing Fees</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox
                  v-model="cols.propertyCashOutValue"
                  binary
                  input-id="property_cash_out_value_col"
                />
                <label for="property_cash_out_value_col">Property Cash Out Value</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.mortgageDebt" binary input-id="mortgage_debt_col" />
                <label for="mortgage_debt_col">Mortgage Debt</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.mortgagePaid" binary input-id="mortgage_paid_col" />
                <label for="mortgage_paid_col">Mortgage Paid</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.cashAvailable" binary input-id="cash_available_col" />
                <label for="cash_available_col">Cash Available</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.cashSpent" binary input-id="cash_spent_col" />
                <label for="cash_spent_col">Cash Spent</label>
              </div>

              <div class="flex items-center gap-2">
                <Checkbox v-model="cols.cashProfit" binary input-id="cash_profit_col" />
                <label for="cash_profit_col">Cash Profit</label>
              </div>
            </div>
          </div>

          <div class="flex items-center gap-4">
            <div class="font-medium">Group By:</div>

            <div class="flex items-center gap-2">
              <RadioButton
                v-model="groupBy"
                input-id="group_by_days"
                name="group_by"
                value="days"
              />
              <label for="group_by_days">Days</label>
            </div>

            <div class="flex items-center gap-2">
              <RadioButton
                v-model="groupBy"
                input-id="group_by_months"
                name="group_by"
                value="months"
              />
              <label for="group_by_months">Months</label>
            </div>

            <div class="flex items-center gap-2">
              <RadioButton
                v-model="groupBy"
                input-id="group_by_years"
                name="group_by"
                value="years"
              />
              <label for="group_by_years">Years</label>
            </div>
          </div>
        </div>

        <table class="table-fixed border-separate border-spacing-4 mt-2">
          <thead class="text-left">
            <tr>
              <th v-if="cols.days">Days</th>
              <th v-if="cols.months">Months</th>
              <th v-if="cols.years">Years</th>
              <th v-if="cols.day">Day</th>
              <th v-if="cols.month">Month</th>
              <th v-if="cols.year">Year</th>
              <th v-if="cols.propertyValue">Property Value</th>
              <th v-if="cols.propertyPurchaseFee">Property Purchase Fee</th>
              <th v-if="cols.propertyPurchasePrice">Property Purchase Price</th>
              <th v-if="cols.propertyMonthlyMaintenaceCost">Property Monthly Maintenance Cost</th>
              <th v-if="cols.propertyMaintenanceCashSpent">Property Maintenance Cash Spent</th>
              <th v-if="cols.propertyClosingFees">Property Cash Out Fee</th>
              <th v-if="cols.propertyCashOutValue">Property Cash Out Value</th>
              <th v-if="cols.mortgageDebt">Mortgage Debt</th>
              <th v-if="cols.mortgagePaid">Mortgage Paid</th>
              <th v-if="cols.cashAvailable">
                <span class="align-middle">Cash Available </span>
                <i
                  class="pi pi-info-circle align-middle ml-1"
                  v-tooltip="{
                    value:
                      'This is how much cash you have available to you if you cash out on all your properties and pay off all of your debts.',
                    autoHide: false,
                  }"
                ></i>
              </th>
              <th v-if="cols.cashSpent">
                <span class="align-middle">Cash Spent </span>
                <i
                  class="pi pi-info-circle align-middle ml-1"
                  v-tooltip="{
                    value:
                      'This is how much you have spent in cash so far from investment purchase fees, deposits, and maintenance costs.',
                    autoHide: false,
                  }"
                ></i>
              </th>
              <th v-if="cols.cashProfit">
                <span class="align-middle">Cash Profit </span>
                <i
                  class="pi pi-info-circle align-middle ml-1"
                  v-tooltip="{
                    value:
                      'This is how much better off you\'d be if you cashed out on all your properties and paid off all of your debts versus never making any investments.',
                    autoHide: false,
                  }"
                ></i>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in rows" :key="row.day">
              <td v-if="cols.days">{{ row.days }}</td>
              <td v-if="cols.months">{{ row.months }}</td>
              <td v-if="cols.years">{{ row.years }}</td>
              <td v-if="cols.day">{{ row.day }}</td>
              <td v-if="cols.month">{{ row.month }}</td>
              <td v-if="cols.year">{{ row.year }}</td>
              <td v-if="cols.propertyValue">{{ row.propertyValue }}</td>
              <td v-if="cols.propertyPurchaseFee">{{ row.propertyPurchaseFee }}</td>
              <td v-if="cols.propertyPurchasePrice">{{ row.propertyPurchasePrice }}</td>
              <td v-if="cols.propertyMonthlyMaintenaceCost">
                {{ row.propertyMonthlyMaintenaceCost }}
              </td>
              <td v-if="cols.propertyMaintenanceCashSpent">
                {{ row.propertyMaintenanceCashSpent }}
              </td>
              <td v-if="cols.propertyClosingFees">{{ row.propertyClosingFees }}</td>
              <td v-if="cols.propertyCashOutValue">{{ row.propertyCashOutValue }}</td>
              <td v-if="cols.mortgageDebt">{{ row.mortgageDebt }}</td>
              <td v-if="cols.mortgagePaid">{{ row.mortgagePaid }}</td>
              <td v-if="cols.cashAvailable">{{ row.cashAvailable }}</td>
              <td v-if="cols.cashSpent">{{ row.cashSpent }}</td>
              <td v-if="cols.cashProfit">{{ row.cashProfit }}</td>
            </tr>
          </tbody>
        </table>
      </AppPanel>
    </main>

    <ScrollTop />
  </AppLayout>
</template>
