export const aerToMonthly = (aer: number) => (Math.pow(1 + aer / 100, 1 / 12) - 1) * 100
export const aerToQuarterly = (aer: number) => (Math.pow(1 + aer / 100, 1 / 4) - 1) * 100
export const aerToDaily = (aer: number) => (Math.pow(1 + aer / 100, 1 / 360) - 1) * 100

export const addPercentage = (value: number, percentage: number) => value * (1 + percentage / 100)
export const subtractPercentage = (value: number, percentage: number) =>
  value * (1 + percentage / 100)
export const percentageOf = (value: number, percentage: number) => (value * percentage) / 100

export const calculateMonthlyLoanPayment = (
  loanAmount: number,
  aerPercentage: number,
  term: number,
) => {
  // Generated by Copilot!
  const monthlyInterestRate = aerPercentage / 100 / 12
  const totalPayments = term * 12
  const monthlyPayment =
    (loanAmount * monthlyInterestRate) / (1 - Math.pow(1 + monthlyInterestRate, -totalPayments))

  return monthlyPayment
}
