import type { InterestRateType } from '@/components/LoanModal.vue'

export const addPercentage = (value: number, percentage: number) => value * (1 + percentage / 100)
export const subtractPercentage = (value: number, percentage: number) =>
  value * (1 + percentage / 100)
export const percentageOf = (value: number, percentage: number) => (value * percentage) / 100

// periodsPerYear is the number of times the interest is compounded per year
// e.g. 12 for monthly, 4 for quarterly, 1 for annual
const aerToPeriodic = (aer: number, periodsPerYear: number) =>
  (Math.pow(1 + aer / 100, 1 / periodsPerYear) - 1) * 100

export const aerToMonthly = (aer: number) => aerToPeriodic(aer, 12)

export const annualToMonthlyInterestRatePercentage = (
  annualRatePercentage: number,
  interestType: InterestRateType,
) => {
  if (interestType === 'nominal') {
    return annualRatePercentage / 12
  }

  if (interestType === 'effective') {
    return aerToMonthly(annualRatePercentage)
  }

  throw new Error(`Unknown interest type: ${interestType}`)
}

// compoundingFrequency is the number of times the interest is compounded per year
// e.g. 12 for monthly, 4 for quarterly, 1 for annual
export const nominalToEffectiveInterestRatePercentage = (
  nominalRatePercentage: number,
  compoundingFrequency: number,
) => {
  const nominalRate = nominalRatePercentage / 100
  const effectiveRate = Math.pow(1 + nominalRate / compoundingFrequency, compoundingFrequency) - 1
  const effectiveRatePercentage = effectiveRate * 100
  return effectiveRatePercentage
}

export const calculateMonthlyLoanPayment = (
  loanAmount: number,
  annualInterestRatePercentage: number,
  interestRateType: InterestRateType,
  term: number,
) => {
  // Generated by Copilot!
  const monthlyInterestRate =
    annualToMonthlyInterestRatePercentage(annualInterestRatePercentage, interestRateType) / 100
  const totalPayments = term * 12
  const monthlyPayment =
    (loanAmount * monthlyInterestRate) / (1 - Math.pow(1 + monthlyInterestRate, -totalPayments))

  return monthlyPayment
}
